
# packages ----------------------------------------------------------------


library(DT)
library(shiny)
library(leaflet)
library(sf)
library(dplyr)
library(readxl)
library(shinythemes)
library(shinyWidgets)
library(ggplot2)
library(plotly)
library(bslib)
library(scales)
library(knitr)
library(kableExtra)
library(tinytex)
library(paletteer)
library(viridis)
library(gridExtra)
library(ggrepel)
library(htmltools)
library(tidyr)
library(shinyjs)
library(htmltools)
library(chilemapas)
library(shinydashboard)
